# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_add_dialogue.ui'
#
# Created: Fri Jul 31 15:07:08 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_add_menu_dialogue(object):
    def setupUi(self, add_menu_dialogue):
        add_menu_dialogue.setObjectName("add_menu_dialogue")
        add_menu_dialogue.resize(527, 479)
        add_menu_dialogue.setStyleSheet("")
        self.verticalLayout = QtGui.QVBoxLayout(add_menu_dialogue)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(add_menu_dialogue)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.menudialogue_codenumber_linedit = QtGui.QLineEdit(add_menu_dialogue)
        self.menudialogue_codenumber_linedit.setObjectName("menudialogue_codenumber_linedit")
        self.horizontalLayout.addWidget(self.menudialogue_codenumber_linedit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(add_menu_dialogue)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(add_menu_dialogue)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.menudialogue_itemname_linedit = QtGui.QLineEdit(add_menu_dialogue)
        self.menudialogue_itemname_linedit.setObjectName("menudialogue_itemname_linedit")
        self.gridLayout_2.addWidget(self.menudialogue_itemname_linedit, 0, 1, 1, 1)
        self.menudialogue_rate_lineedit = QtGui.QLineEdit(add_menu_dialogue)
        self.menudialogue_rate_lineedit.setObjectName("menudialogue_rate_lineedit")
        self.gridLayout_2.addWidget(self.menudialogue_rate_lineedit, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(add_menu_dialogue)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(add_menu_dialogue)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.menudialogue_itemcategory_combobox = QtGui.QComboBox(add_menu_dialogue)
        self.menudialogue_itemcategory_combobox.setObjectName("menudialogue_itemcategory_combobox")
        self.gridLayout_2.addWidget(self.menudialogue_itemcategory_combobox, 1, 1, 1, 1)
        self.menudialogue_serve_lineedit = QtGui.QLineEdit(add_menu_dialogue)
        self.menudialogue_serve_lineedit.setObjectName("menudialogue_serve_lineedit")
        self.gridLayout_2.addWidget(self.menudialogue_serve_lineedit, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(add_menu_dialogue)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.menudialogu_delete_button = QtGui.QPushButton(add_menu_dialogue)
        self.menudialogu_delete_button.setObjectName("menudialogu_delete_button")
        self.gridLayout.addWidget(self.menudialogu_delete_button, 4, 0, 1, 1)
        self.menudialogue_add_button = QtGui.QPushButton(add_menu_dialogue)
        self.menudialogue_add_button.setObjectName("menudialogue_add_button")
        self.gridLayout.addWidget(self.menudialogue_add_button, 4, 2, 1, 1)
        self.menudialogue_newcategory_button = QtGui.QPushButton(add_menu_dialogue)
        self.menudialogue_newcategory_button.setObjectName("menudialogue_newcategory_button")
        self.gridLayout.addWidget(self.menudialogue_newcategory_button, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.menudialogue_menuIngredients_table = QtGui.QTableWidget(add_menu_dialogue)
        self.menudialogue_menuIngredients_table.setObjectName("menudialogue_menuIngredients_table")
        self.menudialogue_menuIngredients_table.setColumnCount(5)
        self.menudialogue_menuIngredients_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.menudialogue_menuIngredients_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.menudialogue_menuIngredients_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.menudialogue_menuIngredients_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.menudialogue_menuIngredients_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.menudialogue_menuIngredients_table.setHorizontalHeaderItem(4, item)
        self.menudialogue_menuIngredients_table.horizontalHeader().setCascadingSectionResizes(True)
        self.menudialogue_menuIngredients_table.horizontalHeader().setSortIndicatorShown(False)
        self.menudialogue_menuIngredients_table.horizontalHeader().setStretchLastSection(True)
        self.menudialogue_menuIngredients_table.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_3.addWidget(self.menudialogue_menuIngredients_table, 0, 0, 1, 2)
        self.menudialogue_menuIngredients_table_addrow_button = QtGui.QPushButton(add_menu_dialogue)
        self.menudialogue_menuIngredients_table_addrow_button.setObjectName("menudialogue_menuIngredients_table_addrow_button")
        self.gridLayout_3.addWidget(self.menudialogue_menuIngredients_table_addrow_button, 1, 0, 1, 1)
        self.menudialogue_menuIngredients_table_save_button = QtGui.QPushButton(add_menu_dialogue)
        self.menudialogue_menuIngredients_table_save_button.setObjectName("menudialogue_menuIngredients_table_save_button")
        self.gridLayout_3.addWidget(self.menudialogue_menuIngredients_table_save_button, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(add_menu_dialogue)
        QtCore.QMetaObject.connectSlotsByName(add_menu_dialogue)
        add_menu_dialogue.setTabOrder(self.menudialogue_codenumber_linedit, self.menudialogue_itemname_linedit)
        add_menu_dialogue.setTabOrder(self.menudialogue_itemname_linedit, self.menudialogue_itemcategory_combobox)
        add_menu_dialogue.setTabOrder(self.menudialogue_itemcategory_combobox, self.menudialogue_rate_lineedit)
        add_menu_dialogue.setTabOrder(self.menudialogue_rate_lineedit, self.menudialogue_serve_lineedit)
        add_menu_dialogue.setTabOrder(self.menudialogue_serve_lineedit, self.menudialogue_add_button)
        add_menu_dialogue.setTabOrder(self.menudialogue_add_button, self.menudialogu_delete_button)
        add_menu_dialogue.setTabOrder(self.menudialogu_delete_button, self.menudialogue_menuIngredients_table)
        add_menu_dialogue.setTabOrder(self.menudialogue_menuIngredients_table, self.menudialogue_menuIngredients_table_save_button)
        add_menu_dialogue.setTabOrder(self.menudialogue_menuIngredients_table_save_button, self.menudialogue_menuIngredients_table_addrow_button)
        add_menu_dialogue.setTabOrder(self.menudialogue_menuIngredients_table_addrow_button, self.menudialogue_newcategory_button)

    def retranslateUi(self, add_menu_dialogue):
        add_menu_dialogue.setWindowTitle(QtGui.QApplication.translate("add_menu_dialogue", "New Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("add_menu_dialogue", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("add_menu_dialogue", "Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("add_menu_dialogue", "Item Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("add_menu_dialogue", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("add_menu_dialogue", "Serve", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogu_delete_button.setText(QtGui.QApplication.translate("add_menu_dialogue", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_add_button.setText(QtGui.QApplication.translate("add_menu_dialogue", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_newcategory_button.setText(QtGui.QApplication.translate("add_menu_dialogue", "New Category", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table.setSortingEnabled(False)
        self.menudialogue_menuIngredients_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("add_menu_dialogue", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("add_menu_dialogue", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("add_menu_dialogue", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("add_menu_dialogue", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("add_menu_dialogue", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table_addrow_button.setText(QtGui.QApplication.translate("add_menu_dialogue", "New Ingredients", None, QtGui.QApplication.UnicodeUTF8))
        self.menudialogue_menuIngredients_table_save_button.setText(QtGui.QApplication.translate("add_menu_dialogue", "Save Ingredients", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    add_menu_dialogue = QtGui.QDialog()
    ui = Ui_add_menu_dialogue()
    ui.setupUi(add_menu_dialogue)
    add_menu_dialogue.show()
    sys.exit(app.exec_())

