image: python2.7
env:
  - POSTGRESQL_URI=postgresql://postgres@127.0.0.1:5432/
  - MYSQL_URI=mysql://root@127.0.0.1:3306/
script:
  - pip install tox
  - tox -e "py27-{sqlite,postgresql}"
services:
  - postgres
