# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keymap.ui'
#
# Created: Tue Jul 28 19:06:52 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 1868)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.key_global_quit = CustomLine(Form)
        self.key_global_quit.setObjectName("key_global_quit")
        self.gridLayout_6.addWidget(self.key_global_quit, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.label_3 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.key_tabs_inventory = CustomLine(Form)
        self.key_tabs_inventory.setObjectName("key_tabs_inventory")
        self.gridLayout.addWidget(self.key_tabs_inventory, 0, 1, 2, 1)
        self.label_7 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.key_tabs_billing = CustomLine(Form)
        self.key_tabs_billing.setObjectName("key_tabs_billing")
        self.gridLayout.addWidget(self.key_tabs_billing, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 2, 1)
        self.key_tabs_employee = CustomLine(Form)
        self.key_tabs_employee.setObjectName("key_tabs_employee")
        self.gridLayout.addWidget(self.key_tabs_employee, 1, 3, 2, 1)
        self.label_5 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.key_tabs_menu = CustomLine(Form)
        self.key_tabs_menu.setObjectName("key_tabs_menu")
        self.gridLayout.addWidget(self.key_tabs_menu, 2, 1, 2, 1)
        self.label_9 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 2, 1)
        self.key_tabs_waste = CustomLine(Form)
        self.key_tabs_waste.setObjectName("key_tabs_waste")
        self.gridLayout.addWidget(self.key_tabs_waste, 3, 3, 2, 1)
        self.label_6 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.key_tabs_report = CustomLine(Form)
        self.key_tabs_report.setObjectName("key_tabs_report")
        self.gridLayout.addWidget(self.key_tabs_report, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_10 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 15, 2, 1, 1)
        self.key_tabcon_inventoryadd_newrow = CustomLine(Form)
        self.key_tabcon_inventoryadd_newrow.setText("")
        self.key_tabcon_inventoryadd_newrow.setObjectName("key_tabcon_inventoryadd_newrow")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryadd_newrow, 4, 3, 1, 1)
        self.key_tabcon_inventorypurchase_search = CustomLine(Form)
        self.key_tabcon_inventorypurchase_search.setText("")
        self.key_tabcon_inventorypurchase_search.setObjectName("key_tabcon_inventorypurchase_search")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_search, 10, 3, 1, 1)
        self.label_26 = QtGui.QLabel(Form)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 8, 2, 1, 1)
        self.label_21 = QtGui.QLabel(Form)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 4, 4, 1, 1)
        self.key_tabcon_inventorypurchase_additem = CustomLine(Form)
        self.key_tabcon_inventorypurchase_additem.setText("")
        self.key_tabcon_inventorypurchase_additem.setObjectName("key_tabcon_inventorypurchase_additem")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_additem, 10, 5, 1, 1)
        self.key_tabcon_inventoryitem_addnewitem = CustomLine(Form)
        self.key_tabcon_inventoryitem_addnewitem.setObjectName("key_tabcon_inventoryitem_addnewitem")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryitem_addnewitem, 17, 3, 1, 1)
        self.key_tabcon_inventoryrelease_release = CustomLine(Form)
        self.key_tabcon_inventoryrelease_release.setText("")
        self.key_tabcon_inventoryrelease_release.setObjectName("key_tabcon_inventoryrelease_release")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryrelease_release, 8, 3, 1, 1)
        self.label_11 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 2)
        self.label_25 = QtGui.QLabel(Form)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 6, 4, 1, 1)
        self.label_22 = QtGui.QLabel(Form)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)
        self.key_tabcon_inventoryrelease_todaysrelease = CustomLine(Form)
        self.key_tabcon_inventoryrelease_todaysrelease.setText("")
        self.key_tabcon_inventoryrelease_todaysrelease.setObjectName("key_tabcon_inventoryrelease_todaysrelease")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryrelease_todaysrelease, 6, 3, 1, 1)
        self.label_34 = QtGui.QLabel(Form)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 10, 2, 1, 1)
        self.label_29 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 9, 1, 1, 5)
        self.key_tabcon_inventorypurchase_print = CustomLine(Form)
        self.key_tabcon_inventorypurchase_print.setText("")
        self.key_tabcon_inventorypurchase_print.setObjectName("key_tabcon_inventorypurchase_print")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_print, 11, 3, 1, 1)
        self.key_tabcon_inventoryadd_addstock = CustomLine(Form)
        self.key_tabcon_inventoryadd_addstock.setText("")
        self.key_tabcon_inventoryadd_addstock.setObjectName("key_tabcon_inventoryadd_addstock")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryadd_addstock, 4, 5, 1, 1)
        self.label_30 = QtGui.QLabel(Form)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 10, 4, 1, 1)
        self.key_tabcon_inventorysupplier_add = CustomLine(Form)
        self.key_tabcon_inventorysupplier_add.setObjectName("key_tabcon_inventorysupplier_add")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorysupplier_add, 15, 3, 1, 1)
        self.key_tabcon_inventoryrelease_addnewrow = CustomLine(Form)
        self.key_tabcon_inventoryrelease_addnewrow.setText("")
        self.key_tabcon_inventoryrelease_addnewrow.setObjectName("key_tabcon_inventoryrelease_addnewrow")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryrelease_addnewrow, 7, 3, 1, 1)
        self.key_tabcon_inventoryrelease_discard = CustomLine(Form)
        self.key_tabcon_inventoryrelease_discard.setText("")
        self.key_tabcon_inventoryrelease_discard.setObjectName("key_tabcon_inventoryrelease_discard")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryrelease_discard, 7, 5, 1, 1)
        self.key_tabcon_inventorypurchase_thismonth = CustomLine(Form)
        self.key_tabcon_inventorypurchase_thismonth.setText("")
        self.key_tabcon_inventorypurchase_thismonth.setObjectName("key_tabcon_inventorypurchase_thismonth")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_thismonth, 12, 5, 1, 1)
        self.key_tabcon_inventorystock_refresh = CustomLine(Form)
        self.key_tabcon_inventorystock_refresh.setObjectName("key_tabcon_inventorystock_refresh")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorystock_refresh, 2, 3, 1, 1)
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(Form)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 7, 4, 1, 1)
        self.key_tabcon_inventorystock_print = CustomLine(Form)
        self.key_tabcon_inventorystock_print.setObjectName("key_tabcon_inventorystock_print")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorystock_print, 2, 5, 1, 1)
        self.key_tabcon_inventorypurchase_today = CustomLine(Form)
        self.key_tabcon_inventorypurchase_today.setText("")
        self.key_tabcon_inventorypurchase_today.setObjectName("key_tabcon_inventorypurchase_today")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_today, 11, 5, 1, 1)
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 4, 1, 1)
        self.label_24 = QtGui.QLabel(Form)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 6, 2, 1, 1)
        self.key_tabcon_inventoryrelease_newrow = CustomLine(Form)
        self.key_tabcon_inventoryrelease_newrow.setText("")
        self.key_tabcon_inventoryrelease_newrow.setObjectName("key_tabcon_inventoryrelease_newrow")
        self.gridLayout_2.addWidget(self.key_tabcon_inventoryrelease_newrow, 6, 5, 1, 1)
        self.label_28 = QtGui.QLabel(Form)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 7, 2, 1, 1)
        self.label_41 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 17, 2, 1, 1)
        self.key_tabcon_inventorypurchase_tommorow = CustomLine(Form)
        self.key_tabcon_inventorypurchase_tommorow.setText("")
        self.key_tabcon_inventorypurchase_tommorow.setObjectName("key_tabcon_inventorypurchase_tommorow")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_tommorow, 12, 3, 1, 1)
        self.key_tabcon_inventorypurchase_thisweek = CustomLine(Form)
        self.key_tabcon_inventorypurchase_thisweek.setText("")
        self.key_tabcon_inventorypurchase_thisweek.setObjectName("key_tabcon_inventorypurchase_thisweek")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_thisweek, 13, 3, 1, 1)
        self.key_tabcon_inventorypurchase_clear = CustomLine(Form)
        self.key_tabcon_inventorypurchase_clear.setText("")
        self.key_tabcon_inventorypurchase_clear.setObjectName("key_tabcon_inventorypurchase_clear")
        self.gridLayout_2.addWidget(self.key_tabcon_inventorypurchase_clear, 13, 5, 1, 1)
        self.label_17 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 1, 1, 5)
        self.label_20 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 1, 1, 5)
        self.label_23 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 5, 1, 1, 5)
        self.label_39 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 14, 1, 1, 5)
        self.label_40 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 16, 1, 1, 5)
        self.label_33 = QtGui.QLabel(Form)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 11, 2, 1, 1)
        self.label_32 = QtGui.QLabel(Form)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 11, 4, 1, 1)
        self.label_31 = QtGui.QLabel(Form)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 12, 2, 1, 1)
        self.label_35 = QtGui.QLabel(Form)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 12, 4, 1, 1)
        self.label_37 = QtGui.QLabel(Form)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 13, 2, 1, 1)
        self.label_36 = QtGui.QLabel(Form)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 13, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.key_tabcon_billingbills_search = CustomLine(Form)
        self.key_tabcon_billingbills_search.setObjectName("key_tabcon_billingbills_search")
        self.gridLayout_3.addWidget(self.key_tabcon_billingbills_search, 3, 2, 1, 1)
        self.label_45 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 2, 3, 1, 1)
        self.label_44 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 1, 1, 1, 4)
        self.label_43 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 2, 1, 1, 1)
        self.key_tabcon_billingbills_reset = CustomLine(Form)
        self.key_tabcon_billingbills_reset.setObjectName("key_tabcon_billingbills_reset")
        self.gridLayout_3.addWidget(self.key_tabcon_billingbills_reset, 2, 4, 1, 1)
        self.label_42 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 0, 0, 1, 1)
        self.key_tabcon_billingedit_pay = CustomLine(Form)
        self.key_tabcon_billingedit_pay.setObjectName("key_tabcon_billingedit_pay")
        self.gridLayout_3.addWidget(self.key_tabcon_billingedit_pay, 5, 2, 1, 1)
        self.label_46 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 3, 1, 1, 1)
        self.key_tabcon_billingbills_newbill = CustomLine(Form)
        self.key_tabcon_billingbills_newbill.setObjectName("key_tabcon_billingbills_newbill")
        self.gridLayout_3.addWidget(self.key_tabcon_billingbills_newbill, 2, 2, 1, 1)
        self.label_73 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 5, 1, 1, 1)
        self.label_47 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 5, 3, 1, 1)
        self.key_tabcon_billingedit_save = CustomLine(Form)
        self.key_tabcon_billingedit_save.setObjectName("key_tabcon_billingedit_save")
        self.gridLayout_3.addWidget(self.key_tabcon_billingedit_save, 5, 4, 1, 1)
        self.label_75 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 6, 1, 1, 1)
        self.key_tabcon_billingedit_print = CustomLine(Form)
        self.key_tabcon_billingedit_print.setObjectName("key_tabcon_billingedit_print")
        self.gridLayout_3.addWidget(self.key_tabcon_billingedit_print, 6, 2, 1, 1)
        self.label_74 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 4, 1, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.key_tabcon_empmgtpayroll_save = CustomLine(Form)
        self.key_tabcon_empmgtpayroll_save.setText("")
        self.key_tabcon_empmgtpayroll_save.setObjectName("key_tabcon_empmgtpayroll_save")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtpayroll_save, 7, 4, 1, 1)
        self.label_55 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_4.addWidget(self.label_55, 5, 1, 1, 1)
        self.key_tabcon_empmgtattendence_save = CustomLine(Form)
        self.key_tabcon_empmgtattendence_save.setText("")
        self.key_tabcon_empmgtattendence_save.setObjectName("key_tabcon_empmgtattendence_save")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtattendence_save, 5, 2, 1, 1)
        self.key_tabcon_empmgtpayroll_search = CustomLine(Form)
        self.key_tabcon_empmgtpayroll_search.setObjectName("key_tabcon_empmgtpayroll_search")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtpayroll_search, 7, 2, 1, 1)
        self.label_59 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_4.addWidget(self.label_59, 9, 1, 1, 1)
        self.key_tabcon_empmgtemployee_view = CustomLine(Form)
        self.key_tabcon_empmgtemployee_view.setObjectName("key_tabcon_empmgtemployee_view")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtemployee_view, 2, 4, 1, 1)
        self.key_tabcon_empmgtshift_view = CustomLine(Form)
        self.key_tabcon_empmgtshift_view.setObjectName("key_tabcon_empmgtshift_view")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtshift_view, 9, 2, 1, 1)
        self.label_58 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_4.addWidget(self.label_58, 7, 1, 1, 1)
        self.key_tabcon_empmgtattendence_search = CustomLine(Form)
        self.key_tabcon_empmgtattendence_search.setObjectName("key_tabcon_empmgtattendence_search")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtattendence_search, 4, 2, 1, 1)
        self.label_50 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 2, 3, 1, 1)
        self.label_61 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_4.addWidget(self.label_61, 9, 3, 1, 1)
        self.key_tabcon_empmgtemployee_add = CustomLine(Form)
        self.key_tabcon_empmgtemployee_add.setObjectName("key_tabcon_empmgtemployee_add")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtemployee_add, 2, 2, 1, 1)
        self.key_tabcon_empmgtshift_add = CustomLine(Form)
        self.key_tabcon_empmgtshift_add.setText("")
        self.key_tabcon_empmgtshift_add.setObjectName("key_tabcon_empmgtshift_add")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtshift_add, 9, 4, 1, 1)
        self.label_54 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_4.addWidget(self.label_54, 4, 1, 1, 1)
        self.key_tabcon_empmgtattendence_create = CustomLine(Form)
        self.key_tabcon_empmgtattendence_create.setObjectName("key_tabcon_empmgtattendence_create")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtattendence_create, 4, 4, 1, 1)
        self.label_48 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 2, 1, 1, 1)
        self.label_57 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_4.addWidget(self.label_57, 7, 3, 1, 1)
        self.label_53 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_4.addWidget(self.label_53, 4, 3, 1, 1)
        self.key_tabcon_empmgtsal_view = CustomLine(Form)
        self.key_tabcon_empmgtsal_view.setObjectName("key_tabcon_empmgtsal_view")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtsal_view, 11, 2, 1, 1)
        self.key_tabcon_empmgtsal_new = CustomLine(Form)
        self.key_tabcon_empmgtsal_new.setText("")
        self.key_tabcon_empmgtsal_new.setObjectName("key_tabcon_empmgtsal_new")
        self.gridLayout_4.addWidget(self.key_tabcon_empmgtsal_new, 11, 4, 1, 1)
        self.label_64 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 11, 3, 1, 1)
        self.label_62 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_4.addWidget(self.label_62, 11, 1, 1, 1)
        self.label_49 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 0, 0, 1, 2)
        self.label_52 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.label_52, 3, 1, 1, 4)
        self.label_56 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 6, 1, 1, 4)
        self.label_60 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_4.addWidget(self.label_60, 8, 1, 1, 4)
        self.label_51 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 1, 1, 1, 4)
        self.label_63 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_4.addWidget(self.label_63, 10, 1, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_71 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_5.addWidget(self.label_71, 3, 1, 1, 4)
        self.label_65 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_5.addWidget(self.label_65, 0, 0, 1, 2)
        self.key_tabcon_menumgtmonsun_refresh = CustomLine(Form)
        self.key_tabcon_menumgtmonsun_refresh.setObjectName("key_tabcon_menumgtmonsun_refresh")
        self.gridLayout_5.addWidget(self.key_tabcon_menumgtmonsun_refresh, 4, 4, 1, 1)
        self.label_68 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_5.addWidget(self.label_68, 1, 1, 1, 4)
        self.label_69 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_5.addWidget(self.label_69, 4, 1, 1, 1)
        self.key_tabcon_menumgtmenu_add = CustomLine(Form)
        self.key_tabcon_menumgtmenu_add.setText("")
        self.key_tabcon_menumgtmenu_add.setObjectName("key_tabcon_menumgtmenu_add")
        self.gridLayout_5.addWidget(self.key_tabcon_menumgtmenu_add, 2, 4, 1, 1)
        self.key_tabcon_menumgtmonsun_add = CustomLine(Form)
        self.key_tabcon_menumgtmonsun_add.setObjectName("key_tabcon_menumgtmonsun_add")
        self.gridLayout_5.addWidget(self.key_tabcon_menumgtmonsun_add, 5, 2, 1, 1)
        self.label_67 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_5.addWidget(self.label_67, 2, 3, 1, 1)
        self.label_70 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_5.addWidget(self.label_70, 5, 1, 1, 1)
        self.key_tabcon_menumgtmonsun_view = CustomLine(Form)
        self.key_tabcon_menumgtmonsun_view.setText("")
        self.key_tabcon_menumgtmonsun_view.setObjectName("key_tabcon_menumgtmonsun_view")
        self.gridLayout_5.addWidget(self.key_tabcon_menumgtmonsun_view, 4, 2, 1, 1)
        self.key_tabcon_menumgtmenu_view = CustomLine(Form)
        self.key_tabcon_menumgtmenu_view.setObjectName("key_tabcon_menumgtmenu_view")
        self.gridLayout_5.addWidget(self.key_tabcon_menumgtmenu_view, 2, 2, 1, 1)
        self.label_66 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_5.addWidget(self.label_66, 2, 1, 1, 1)
        self.label_72 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_5.addWidget(self.label_72, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.key_resetdefault_button = QtGui.QPushButton(Form)
        self.key_resetdefault_button.setObjectName("key_resetdefault_button")
        self.horizontalLayout.addWidget(self.key_resetdefault_button)
        self.key_apply_button = QtGui.QPushButton(Form)
        self.key_apply_button.setObjectName("key_apply_button")
        self.horizontalLayout.addWidget(self.key_apply_button)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.key_global_quit, self.key_tabs_inventory)
        Form.setTabOrder(self.key_tabs_inventory, self.key_tabs_billing)
        Form.setTabOrder(self.key_tabs_billing, self.key_tabs_menu)
        Form.setTabOrder(self.key_tabs_menu, self.key_tabs_employee)
        Form.setTabOrder(self.key_tabs_employee, self.key_tabs_report)
        Form.setTabOrder(self.key_tabs_report, self.key_tabs_waste)
        Form.setTabOrder(self.key_tabs_waste, self.key_tabcon_inventorystock_refresh)
        Form.setTabOrder(self.key_tabcon_inventorystock_refresh, self.key_tabcon_inventorystock_print)
        Form.setTabOrder(self.key_tabcon_inventorystock_print, self.key_tabcon_inventoryadd_newrow)
        Form.setTabOrder(self.key_tabcon_inventoryadd_newrow, self.key_tabcon_inventoryadd_addstock)
        Form.setTabOrder(self.key_tabcon_inventoryadd_addstock, self.key_tabcon_inventoryrelease_todaysrelease)
        Form.setTabOrder(self.key_tabcon_inventoryrelease_todaysrelease, self.key_tabcon_inventoryrelease_newrow)
        Form.setTabOrder(self.key_tabcon_inventoryrelease_newrow, self.key_tabcon_inventoryrelease_addnewrow)
        Form.setTabOrder(self.key_tabcon_inventoryrelease_addnewrow, self.key_tabcon_inventoryrelease_discard)
        Form.setTabOrder(self.key_tabcon_inventoryrelease_discard, self.key_tabcon_inventoryrelease_release)
        Form.setTabOrder(self.key_tabcon_inventoryrelease_release, self.key_tabcon_inventorypurchase_search)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_search, self.key_tabcon_inventorypurchase_additem)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_additem, self.key_tabcon_inventorypurchase_print)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_print, self.key_tabcon_inventorypurchase_today)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_today, self.key_tabcon_inventorypurchase_tommorow)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_tommorow, self.key_tabcon_inventorypurchase_thismonth)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_thismonth, self.key_tabcon_inventorypurchase_thisweek)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_thisweek, self.key_tabcon_inventorypurchase_clear)
        Form.setTabOrder(self.key_tabcon_inventorypurchase_clear, self.key_tabcon_inventorysupplier_add)
        Form.setTabOrder(self.key_tabcon_inventorysupplier_add, self.key_tabcon_inventoryitem_addnewitem)
        Form.setTabOrder(self.key_tabcon_inventoryitem_addnewitem, self.key_tabcon_billingbills_newbill)
        Form.setTabOrder(self.key_tabcon_billingbills_newbill, self.key_tabcon_billingbills_reset)
        Form.setTabOrder(self.key_tabcon_billingbills_reset, self.key_tabcon_billingbills_search)
        Form.setTabOrder(self.key_tabcon_billingbills_search, self.key_tabcon_billingedit_pay)
        Form.setTabOrder(self.key_tabcon_billingedit_pay, self.key_tabcon_billingedit_save)
        Form.setTabOrder(self.key_tabcon_billingedit_save, self.key_tabcon_billingedit_print)
        Form.setTabOrder(self.key_tabcon_billingedit_print, self.key_tabcon_empmgtemployee_add)
        Form.setTabOrder(self.key_tabcon_empmgtemployee_add, self.key_tabcon_empmgtemployee_view)
        Form.setTabOrder(self.key_tabcon_empmgtemployee_view, self.key_tabcon_empmgtattendence_search)
        Form.setTabOrder(self.key_tabcon_empmgtattendence_search, self.key_tabcon_empmgtattendence_create)
        Form.setTabOrder(self.key_tabcon_empmgtattendence_create, self.key_tabcon_empmgtattendence_save)
        Form.setTabOrder(self.key_tabcon_empmgtattendence_save, self.key_tabcon_empmgtpayroll_search)
        Form.setTabOrder(self.key_tabcon_empmgtpayroll_search, self.key_tabcon_empmgtpayroll_save)
        Form.setTabOrder(self.key_tabcon_empmgtpayroll_save, self.key_tabcon_empmgtshift_view)
        Form.setTabOrder(self.key_tabcon_empmgtshift_view, self.key_tabcon_empmgtshift_add)
        Form.setTabOrder(self.key_tabcon_empmgtshift_add, self.key_tabcon_empmgtsal_view)
        Form.setTabOrder(self.key_tabcon_empmgtsal_view, self.key_tabcon_empmgtsal_new)
        Form.setTabOrder(self.key_tabcon_empmgtsal_new, self.key_tabcon_menumgtmenu_view)
        Form.setTabOrder(self.key_tabcon_menumgtmenu_view, self.key_tabcon_menumgtmenu_add)
        Form.setTabOrder(self.key_tabcon_menumgtmenu_add, self.key_tabcon_menumgtmonsun_view)
        Form.setTabOrder(self.key_tabcon_menumgtmonsun_view, self.key_tabcon_menumgtmonsun_refresh)
        Form.setTabOrder(self.key_tabcon_menumgtmonsun_refresh, self.key_tabcon_menumgtmonsun_add)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Inventory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Billing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Waste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Tab Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Add Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Inventory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Insert New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "Purchase Schedule", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "Add Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Today\'s Release", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Add New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Form", "Add New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Form", "Supplier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Form", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "Today", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "Tommorow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Form", "This Month", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Form", "This Week", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Form", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Form", "Reset Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Form", "Bills", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Form", "New Bill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Form", "Billing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("Form", "Pay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("Form", "Edit Bill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("Form", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("Form", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("Form", "Add Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("Form", "Create Attendence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("Form", "New Salary Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("Form", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("Form", "Employee Management", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("Form", "Attendence ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("Form", "Payroll", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("Form", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("Form", "Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("Form", "Salary Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("Form", "Mon-Sun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("Form", "Menu Management", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("Form", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("Form", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("Form", "Add New Dish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("Form", "Add Dish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("Form", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.key_resetdefault_button.setText(QtGui.QApplication.translate("Form", "Reset Default", None, QtGui.QApplication.UnicodeUTF8))
        self.key_apply_button.setText(QtGui.QApplication.translate("Form", "Apply", None, QtGui.QApplication.UnicodeUTF8))

from customline.customline import CustomLine

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

