image: python2.7
env:
  - POSTGRESQL_URI=postgresql://postgres@127.0.0.1:5432/
  - MYSQL_URI=mysql://root@127.0.0.1:3306/
script:
  - sudo apt-get install python-dev libldap2-dev libsasl2-dev libssl-dev
  - pip install tox
  - tox -e sqlite,postgresql
services:
  - postgres
