# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_stack.ui'
#
# Created: Mon Aug  3 19:28:20 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(843, 545)
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.adminFrame = QtGui.QFrame(Form)
        self.adminFrame.setObjectName("adminFrame")
        self.formLayout = QtGui.QFormLayout(self.adminFrame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.adminFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.adminpopup_hotelname_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_hotelname_linedit.setObjectName("adminpopup_hotelname_linedit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.adminpopup_hotelname_linedit)
        self.label_2 = QtGui.QLabel(self.adminFrame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.adminpopup_street_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_street_linedit.setObjectName("adminpopup_street_linedit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.adminpopup_street_linedit)
        self.label_8 = QtGui.QLabel(self.adminFrame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.adminpopup_city_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_city_linedit.setObjectName("adminpopup_city_linedit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.adminpopup_city_linedit)
        self.label_9 = QtGui.QLabel(self.adminFrame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.adminpopup_pin_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_pin_linedit.setObjectName("adminpopup_pin_linedit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.adminpopup_pin_linedit)
        self.label_4 = QtGui.QLabel(self.adminFrame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.adminpopup_latitude_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_latitude_linedit.setObjectName("adminpopup_latitude_linedit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.adminpopup_latitude_linedit)
        self.label_5 = QtGui.QLabel(self.adminFrame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.adminpopup_longitude_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_longitude_linedit.setObjectName("adminpopup_longitude_linedit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.adminpopup_longitude_linedit)
        self.label_3 = QtGui.QLabel(self.adminFrame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.adminpopup_apikey_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_apikey_linedit.setObjectName("adminpopup_apikey_linedit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.adminpopup_apikey_linedit)
        self.label_10 = QtGui.QLabel(self.adminFrame)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.adminpopup_tax_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_tax_linedit.setObjectName("adminpopup_tax_linedit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.adminpopup_tax_linedit)
        self.label_6 = QtGui.QLabel(self.adminFrame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_6)
        self.adminpopup_profileid_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_profileid_linedit.setObjectName("adminpopup_profileid_linedit")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.adminpopup_profileid_linedit)
        self.label_7 = QtGui.QLabel(self.adminFrame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_7)
        self.adminpopup_password_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_password_linedit.setEchoMode(QtGui.QLineEdit.Password)
        self.adminpopup_password_linedit.setObjectName("adminpopup_password_linedit")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.adminpopup_password_linedit)
        self.label_17 = QtGui.QLabel(self.adminFrame)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_17)
        self.adminpopup_fssai_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_fssai_linedit.setObjectName("adminpopup_fssai_linedit")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.adminpopup_fssai_linedit)
        self.label_18 = QtGui.QLabel(self.adminFrame)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_18)
        self.adminpopup_tin_linedit = QtGui.QLineEdit(self.adminFrame)
        self.adminpopup_tin_linedit.setObjectName("adminpopup_tin_linedit")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.adminpopup_tin_linedit)
        self.label_11 = QtGui.QLabel(self.adminFrame)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_11)
        self.adminpopup_dev_checkbox = QtGui.QCheckBox(self.adminFrame)
        self.adminpopup_dev_checkbox.setObjectName("adminpopup_dev_checkbox")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.adminpopup_dev_checkbox)
        self.adminpopup_save_button = QtGui.QPushButton(self.adminFrame)
        self.adminpopup_save_button.setObjectName("adminpopup_save_button")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.adminpopup_save_button)
        self.horizontalLayout_2.addWidget(self.adminFrame)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.assignFrame = QtGui.QFrame(Form)
        self.assignFrame.setObjectName("assignFrame")
        self.gridLayout = QtGui.QGridLayout(self.assignFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.adminpopup_assign_newgroup_button = QtGui.QPushButton(self.assignFrame)
        self.adminpopup_assign_newgroup_button.setObjectName("adminpopup_assign_newgroup_button")
        self.gridLayout.addWidget(self.adminpopup_assign_newgroup_button, 1, 2, 1, 1)
        self.adminpopup_assign_groupname_combobox = QtGui.QComboBox(self.assignFrame)
        self.adminpopup_assign_groupname_combobox.setObjectName("adminpopup_assign_groupname_combobox")
        self.gridLayout.addWidget(self.adminpopup_assign_groupname_combobox, 1, 0, 1, 2)
        self.adminpopup_assign_delete_button = QtGui.QPushButton(self.assignFrame)
        self.adminpopup_assign_delete_button.setObjectName("adminpopup_assign_delete_button")
        self.gridLayout.addWidget(self.adminpopup_assign_delete_button, 5, 0, 1, 1)
        self.adminpopup_assign_addmembers_button = QtGui.QPushButton(self.assignFrame)
        self.adminpopup_assign_addmembers_button.setObjectName("adminpopup_assign_addmembers_button")
        self.gridLayout.addWidget(self.adminpopup_assign_addmembers_button, 5, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.assignFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 3)
        self.adminpopup_assign_members_table = QtGui.QTableWidget(self.assignFrame)
        self.adminpopup_assign_members_table.setObjectName("adminpopup_assign_members_table")
        self.adminpopup_assign_members_table.setColumnCount(1)
        self.adminpopup_assign_members_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.adminpopup_assign_members_table.setHorizontalHeaderItem(0, item)
        self.adminpopup_assign_members_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.adminpopup_assign_members_table, 4, 0, 1, 3)
        self.adminpopup_assign_roles_table = QtGui.QTableWidget(self.assignFrame)
        self.adminpopup_assign_roles_table.setObjectName("adminpopup_assign_roles_table")
        self.adminpopup_assign_roles_table.setColumnCount(1)
        self.adminpopup_assign_roles_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.adminpopup_assign_roles_table.setHorizontalHeaderItem(0, item)
        self.adminpopup_assign_roles_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.adminpopup_assign_roles_table, 2, 0, 1, 3)
        self.adminpopup_assign_deletegroup_button = QtGui.QPushButton(self.assignFrame)
        self.adminpopup_assign_deletegroup_button.setObjectName("adminpopup_assign_deletegroup_button")
        self.gridLayout.addWidget(self.adminpopup_assign_deletegroup_button, 3, 0, 1, 1)
        self.adminpopup_assign_addroles_button = QtGui.QPushButton(self.assignFrame)
        self.adminpopup_assign_addroles_button.setObjectName("adminpopup_assign_addroles_button")
        self.gridLayout.addWidget(self.adminpopup_assign_addroles_button, 3, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.assignFrame)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.createFrame = QtGui.QFrame(Form)
        self.createFrame.setAutoFillBackground(True)
        self.createFrame.setStyleSheet("")
        self.createFrame.setObjectName("createFrame")
        self.formLayout_2 = QtGui.QFormLayout(self.createFrame)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtGui.QLabel(self.createFrame)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_14)
        self.adminpopup_createuser_username_combobox = QtGui.QComboBox(self.createFrame)
        self.adminpopup_createuser_username_combobox.setObjectName("adminpopup_createuser_username_combobox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.adminpopup_createuser_username_combobox)
        self.label_12 = QtGui.QLabel(self.createFrame)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.adminpopup_createuser_username_linedit = QtGui.QLineEdit(self.createFrame)
        self.adminpopup_createuser_username_linedit.setObjectName("adminpopup_createuser_username_linedit")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.adminpopup_createuser_username_linedit)
        self.label_13 = QtGui.QLabel(self.createFrame)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.adminpopup_createuser_password_linedit = QtGui.QLineEdit(self.createFrame)
        self.adminpopup_createuser_password_linedit.setEchoMode(QtGui.QLineEdit.Password)
        self.adminpopup_createuser_password_linedit.setObjectName("adminpopup_createuser_password_linedit")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.adminpopup_createuser_password_linedit)
        self.adminpopup_createuser_delete_button = QtGui.QPushButton(self.createFrame)
        self.adminpopup_createuser_delete_button.setObjectName("adminpopup_createuser_delete_button")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.adminpopup_createuser_delete_button)
        self.adminpopup_createuser_save_button = QtGui.QPushButton(self.createFrame)
        self.adminpopup_createuser_save_button.setObjectName("adminpopup_createuser_save_button")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.adminpopup_createuser_save_button)
        self.adminpopup_createuser_create_button = QtGui.QPushButton(self.createFrame)
        self.adminpopup_createuser_create_button.setObjectName("adminpopup_createuser_create_button")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.SpanningRole, self.adminpopup_createuser_create_button)
        self.adminpopup_createuser_name_linedit = QtGui.QLineEdit(self.createFrame)
        self.adminpopup_createuser_name_linedit.setReadOnly(True)
        self.adminpopup_createuser_name_linedit.setObjectName("adminpopup_createuser_name_linedit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.adminpopup_createuser_name_linedit)
        self.label_16 = QtGui.QLabel(self.createFrame)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_2.addWidget(self.createFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.adminpopup_hotelname_linedit, self.adminpopup_street_linedit)
        Form.setTabOrder(self.adminpopup_street_linedit, self.adminpopup_city_linedit)
        Form.setTabOrder(self.adminpopup_city_linedit, self.adminpopup_pin_linedit)
        Form.setTabOrder(self.adminpopup_pin_linedit, self.adminpopup_latitude_linedit)
        Form.setTabOrder(self.adminpopup_latitude_linedit, self.adminpopup_longitude_linedit)
        Form.setTabOrder(self.adminpopup_longitude_linedit, self.adminpopup_apikey_linedit)
        Form.setTabOrder(self.adminpopup_apikey_linedit, self.adminpopup_tax_linedit)
        Form.setTabOrder(self.adminpopup_tax_linedit, self.adminpopup_profileid_linedit)
        Form.setTabOrder(self.adminpopup_profileid_linedit, self.adminpopup_password_linedit)
        Form.setTabOrder(self.adminpopup_password_linedit, self.adminpopup_fssai_linedit)
        Form.setTabOrder(self.adminpopup_fssai_linedit, self.adminpopup_tin_linedit)
        Form.setTabOrder(self.adminpopup_tin_linedit, self.adminpopup_dev_checkbox)
        Form.setTabOrder(self.adminpopup_dev_checkbox, self.adminpopup_save_button)
        Form.setTabOrder(self.adminpopup_save_button, self.adminpopup_assign_groupname_combobox)
        Form.setTabOrder(self.adminpopup_assign_groupname_combobox, self.adminpopup_assign_newgroup_button)
        Form.setTabOrder(self.adminpopup_assign_newgroup_button, self.adminpopup_assign_roles_table)
        Form.setTabOrder(self.adminpopup_assign_roles_table, self.adminpopup_assign_deletegroup_button)
        Form.setTabOrder(self.adminpopup_assign_deletegroup_button, self.adminpopup_assign_addroles_button)
        Form.setTabOrder(self.adminpopup_assign_addroles_button, self.adminpopup_assign_members_table)
        Form.setTabOrder(self.adminpopup_assign_members_table, self.adminpopup_assign_delete_button)
        Form.setTabOrder(self.adminpopup_assign_delete_button, self.adminpopup_assign_addmembers_button)
        Form.setTabOrder(self.adminpopup_assign_addmembers_button, self.adminpopup_createuser_username_combobox)
        Form.setTabOrder(self.adminpopup_createuser_username_combobox, self.adminpopup_createuser_name_linedit)
        Form.setTabOrder(self.adminpopup_createuser_name_linedit, self.adminpopup_createuser_username_linedit)
        Form.setTabOrder(self.adminpopup_createuser_username_linedit, self.adminpopup_createuser_password_linedit)
        Form.setTabOrder(self.adminpopup_createuser_password_linedit, self.adminpopup_createuser_save_button)
        Form.setTabOrder(self.adminpopup_createuser_save_button, self.adminpopup_createuser_delete_button)
        Form.setTabOrder(self.adminpopup_createuser_delete_button, self.adminpopup_createuser_create_button)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Hotel Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Street & Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Pin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "API Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Profile Id", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "FSSAI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "TIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Developer Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_dev_checkbox.setText(QtGui.QApplication.translate("Form", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_save_button.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_newgroup_button.setText(QtGui.QApplication.translate("Form", "New Group", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_delete_button.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_addmembers_button.setText(QtGui.QApplication.translate("Form", "Add Members", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Assign Roles", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_members_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Members in the Group", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_roles_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Name of Roles", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_deletegroup_button.setText(QtGui.QApplication.translate("Form", "Delete Group", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_assign_addroles_button.setText(QtGui.QApplication.translate("Form", "Add Roles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Create or Edit User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_createuser_delete_button.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_createuser_save_button.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_createuser_create_button.setText(QtGui.QApplication.translate("Form", "Create User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

