# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created: Mon Jun 22 15:32:48 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 429)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.adminpopup_hotelname_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_hotelname_linedit.setObjectName("adminpopup_hotelname_linedit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.adminpopup_hotelname_linedit)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.adminpopup_street_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_street_linedit.setObjectName("adminpopup_street_linedit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.adminpopup_street_linedit)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.adminpopup_city_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_city_linedit.setObjectName("adminpopup_city_linedit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.adminpopup_city_linedit)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.adminpopup_pin_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_pin_linedit.setObjectName("adminpopup_pin_linedit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.adminpopup_pin_linedit)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.adminpopup_latitude_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_latitude_linedit.setObjectName("adminpopup_latitude_linedit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.adminpopup_latitude_linedit)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.adminpopup_longitude_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_longitude_linedit.setObjectName("adminpopup_longitude_linedit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.adminpopup_longitude_linedit)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.adminpopup_apikey_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_apikey_linedit.setObjectName("adminpopup_apikey_linedit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.adminpopup_apikey_linedit)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_6)
        self.adminpopup_profileid_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_profileid_linedit.setObjectName("adminpopup_profileid_linedit")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.adminpopup_profileid_linedit)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_7)
        self.adminpopup_password_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_password_linedit.setEchoMode(QtGui.QLineEdit.Password)
        self.adminpopup_password_linedit.setObjectName("adminpopup_password_linedit")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.adminpopup_password_linedit)
        self.adminpopup_tax_linedit = QtGui.QLineEdit(Dialog)
        self.adminpopup_tax_linedit.setObjectName("adminpopup_tax_linedit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.adminpopup_tax_linedit)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.adminpopup_dev_checkbox = QtGui.QCheckBox(Dialog)
        self.adminpopup_dev_checkbox.setObjectName("adminpopup_dev_checkbox")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.adminpopup_dev_checkbox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.adminpopup_save_button = QtGui.QPushButton(Dialog)
        self.adminpopup_save_button.setObjectName("adminpopup_save_button")
        self.horizontalLayout.addWidget(self.adminpopup_save_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.adminpopup_close_button = QtGui.QPushButton(Dialog)
        self.adminpopup_close_button.setObjectName("adminpopup_close_button")
        self.horizontalLayout.addWidget(self.adminpopup_close_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.adminpopup_hotelname_linedit, self.adminpopup_street_linedit)
        Dialog.setTabOrder(self.adminpopup_street_linedit, self.adminpopup_city_linedit)
        Dialog.setTabOrder(self.adminpopup_city_linedit, self.adminpopup_pin_linedit)
        Dialog.setTabOrder(self.adminpopup_pin_linedit, self.adminpopup_latitude_linedit)
        Dialog.setTabOrder(self.adminpopup_latitude_linedit, self.adminpopup_longitude_linedit)
        Dialog.setTabOrder(self.adminpopup_longitude_linedit, self.adminpopup_apikey_linedit)
        Dialog.setTabOrder(self.adminpopup_apikey_linedit, self.adminpopup_tax_linedit)
        Dialog.setTabOrder(self.adminpopup_tax_linedit, self.adminpopup_profileid_linedit)
        Dialog.setTabOrder(self.adminpopup_profileid_linedit, self.adminpopup_password_linedit)
        Dialog.setTabOrder(self.adminpopup_password_linedit, self.adminpopup_save_button)
        Dialog.setTabOrder(self.adminpopup_save_button, self.adminpopup_close_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Hotel Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Street & Lane", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Pin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "API Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Profile Id", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Developer Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_dev_checkbox.setText(QtGui.QApplication.translate("Dialog", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_save_button.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.adminpopup_close_button.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

