# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee_details_popup.ui'
#
# Created: Wed Jun 10 17:55:57 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 718)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.employeedialogue_employeeid_lineedit = QtGui.QLineEdit(Dialog)
        self.employeedialogue_employeeid_lineedit.setObjectName("employeedialogue_employeeid_lineedit")
        self.horizontalLayout.addWidget(self.employeedialogue_employeeid_lineedit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 620))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 12, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 11, 0, 1, 1)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.employeedialogue_employeedob_dateedit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeedob_dateedit.setCalendarPopup(False)
        self.employeedialogue_employeedob_dateedit.setObjectName("employeedialogue_employeedob_dateedit")
        self.gridLayout.addWidget(self.employeedialogue_employeedob_dateedit, 4, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.employeedialogue_employeeaddress_textedit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeeaddress_textedit.setObjectName("employeedialogue_employeeaddress_textedit")
        self.gridLayout.addWidget(self.employeedialogue_employeeaddress_textedit, 7, 1, 1, 4)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 14, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 13, 0, 1, 1)
        self.employeedialogue_employeedoj_dateedit = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeedoj_dateedit.setCalendarPopup(False)
        self.employeedialogue_employeedoj_dateedit.setObjectName("employeedialogue_employeedoj_dateedit")
        self.gridLayout.addWidget(self.employeedialogue_employeedoj_dateedit, 14, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(144, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 14, 3, 1, 2)
        self.employeedialogue_employeename_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeename_lineedit.setObjectName("employeedialogue_employeename_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeename_lineedit, 0, 1, 1, 4)
        self.employeedialogue_employeesurname_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeesurname_lineedit.setObjectName("employeedialogue_employeesurname_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeesurname_lineedit, 1, 1, 1, 4)
        self.employeedialogue_employeefathername_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeefathername_lineedit.setObjectName("employeedialogue_employeefathername_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeefathername_lineedit, 2, 1, 1, 4)
        self.employeedialogue_employeepan_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeepan_lineedit.setObjectName("employeedialogue_employeepan_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeepan_lineedit, 5, 1, 1, 4)
        self.employeedialogue_employeeadhar_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeeadhar_lineedit.setObjectName("employeedialogue_employeeadhar_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeeadhar_lineedit, 6, 1, 1, 4)
        self.employeedialogue_employeecontact_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeecontact_lineedit.setObjectName("employeedialogue_employeecontact_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeecontact_lineedit, 8, 1, 1, 4)
        self.employeedialogue_employeebasicpay_lineedit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.employeedialogue_employeebasicpay_lineedit.setObjectName("employeedialogue_employeebasicpay_lineedit")
        self.gridLayout.addWidget(self.employeedialogue_employeebasicpay_lineedit, 12, 1, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(47, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 4, 1, 1)
        self.employeedialogue_employeeshift_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.employeedialogue_employeeshift_combobox.setObjectName("employeedialogue_employeeshift_combobox")
        self.gridLayout.addWidget(self.employeedialogue_employeeshift_combobox, 11, 1, 1, 2)
        self.employeedialogue_employeesex_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.employeedialogue_employeesex_combobox.setMaxVisibleItems(3)
        self.employeedialogue_employeesex_combobox.setMaxCount(3)
        self.employeedialogue_employeesex_combobox.setObjectName("employeedialogue_employeesex_combobox")
        self.employeedialogue_employeesex_combobox.addItem("")
        self.employeedialogue_employeesex_combobox.addItem("")
        self.employeedialogue_employeesex_combobox.addItem("")
        self.gridLayout.addWidget(self.employeedialogue_employeesex_combobox, 3, 1, 1, 2)
        self.employeedialogue_employeeperiod_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.employeedialogue_employeeperiod_combobox.setObjectName("employeedialogue_employeeperiod_combobox")
        self.employeedialogue_employeeperiod_combobox.addItem("")
        self.employeedialogue_employeeperiod_combobox.addItem("")
        self.employeedialogue_employeeperiod_combobox.addItem("")
        self.gridLayout.addWidget(self.employeedialogue_employeeperiod_combobox, 13, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 13, 3, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 11, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 10, 0, 1, 1)
        self.employeedialogue_employdesignation_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.employeedialogue_employdesignation_combobox.setObjectName("employeedialogue_employdesignation_combobox")
        self.gridLayout.addWidget(self.employeedialogue_employdesignation_combobox, 9, 1, 1, 2)
        self.employeedialogue_employeedepartment_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.employeedialogue_employeedepartment_combobox.setObjectName("employeedialogue_employeedepartment_combobox")
        self.gridLayout.addWidget(self.employeedialogue_employeedepartment_combobox, 10, 1, 1, 2)
        self.employeedialogue_newdesignation_pushbutton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.employeedialogue_newdesignation_pushbutton.setObjectName("employeedialogue_newdesignation_pushbutton")
        self.gridLayout.addWidget(self.employeedialogue_newdesignation_pushbutton, 9, 3, 1, 2)
        self.employeedialogue_newdepartment_pushbutton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.employeedialogue_newdepartment_pushbutton.setObjectName("employeedialogue_newdepartment_pushbutton")
        self.gridLayout.addWidget(self.employeedialogue_newdepartment_pushbutton, 10, 3, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.employeedialogue_employeedelete_pushbutton = QtGui.QPushButton(Dialog)
        self.employeedialogue_employeedelete_pushbutton.setObjectName("employeedialogue_employeedelete_pushbutton")
        self.horizontalLayout_2.addWidget(self.employeedialogue_employeedelete_pushbutton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.employeedialogue_employeesave_pushbutton = QtGui.QPushButton(Dialog)
        self.employeedialogue_employeesave_pushbutton.setObjectName("employeedialogue_employeesave_pushbutton")
        self.horizontalLayout_2.addWidget(self.employeedialogue_employeesave_pushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.employeedialogue_employeename_lineedit, self.employeedialogue_employeesurname_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeesurname_lineedit, self.employeedialogue_employeefathername_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeefathername_lineedit, self.employeedialogue_employeesex_combobox)
        Dialog.setTabOrder(self.employeedialogue_employeesex_combobox, self.employeedialogue_employeedob_dateedit)
        Dialog.setTabOrder(self.employeedialogue_employeedob_dateedit, self.employeedialogue_employeepan_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeepan_lineedit, self.employeedialogue_employeeadhar_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeeadhar_lineedit, self.employeedialogue_employeeaddress_textedit)
        Dialog.setTabOrder(self.employeedialogue_employeeaddress_textedit, self.employeedialogue_employeecontact_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeecontact_lineedit, self.employeedialogue_employdesignation_combobox)
        Dialog.setTabOrder(self.employeedialogue_employdesignation_combobox, self.employeedialogue_employeedepartment_combobox)
        Dialog.setTabOrder(self.employeedialogue_employeedepartment_combobox, self.employeedialogue_employeeshift_combobox)
        Dialog.setTabOrder(self.employeedialogue_employeeshift_combobox, self.employeedialogue_employeebasicpay_lineedit)
        Dialog.setTabOrder(self.employeedialogue_employeebasicpay_lineedit, self.employeedialogue_employeeperiod_combobox)
        Dialog.setTabOrder(self.employeedialogue_employeeperiod_combobox, self.employeedialogue_employeedoj_dateedit)
        Dialog.setTabOrder(self.employeedialogue_employeedoj_dateedit, self.employeedialogue_employeesave_pushbutton)
        Dialog.setTabOrder(self.employeedialogue_employeesave_pushbutton, self.employeedialogue_newdesignation_pushbutton)
        Dialog.setTabOrder(self.employeedialogue_newdesignation_pushbutton, self.employeedialogue_newdepartment_pushbutton)
        Dialog.setTabOrder(self.employeedialogue_newdepartment_pushbutton, self.employeedialogue_employeedelete_pushbutton)
        Dialog.setTabOrder(self.employeedialogue_employeedelete_pushbutton, self.scrollArea)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Employee Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Basic Pay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Surname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Fathers Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Sex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Date of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeedob_dateedit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "dd-MM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "PAN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Adhar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Contact", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Date of Joining", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeedoj_dateedit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "dd-MM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeesex_combobox.setItemText(0, QtGui.QApplication.translate("Dialog", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeesex_combobox.setItemText(1, QtGui.QApplication.translate("Dialog", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeesex_combobox.setItemText(2, QtGui.QApplication.translate("Dialog", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeeperiod_combobox.setItemText(0, QtGui.QApplication.translate("Dialog", "Monthly", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeeperiod_combobox.setItemText(1, QtGui.QApplication.translate("Dialog", "Weekly", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeeperiod_combobox.setItemText(2, QtGui.QApplication.translate("Dialog", "Daily", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Department", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_newdesignation_pushbutton.setText(QtGui.QApplication.translate("Dialog", "New Designation", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_newdepartment_pushbutton.setText(QtGui.QApplication.translate("Dialog", "New Department", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeedelete_pushbutton.setText(QtGui.QApplication.translate("Dialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.employeedialogue_employeesave_pushbutton.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))

