# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shift_add_popup.ui'
#
# Created: Mon Jun  8 17:11:20 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_shift_popup(object):
    def setupUi(self, shift_popup):
        shift_popup.setObjectName("shift_popup")
        shift_popup.resize(333, 376)
        self.gridLayout_2 = QtGui.QGridLayout(shift_popup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(shift_popup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.shift_name_linedit = QtGui.QLineEdit(shift_popup)
        self.shift_name_linedit.setObjectName("shift_name_linedit")
        self.gridLayout.addWidget(self.shift_name_linedit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(shift_popup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(shift_popup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.shift_mon_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_mon_checkbox.setObjectName("shift_mon_checkbox")
        self.gridLayout.addWidget(self.shift_mon_checkbox, 3, 0, 1, 1)
        self.shift_fri_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_fri_checkbox.setObjectName("shift_fri_checkbox")
        self.gridLayout.addWidget(self.shift_fri_checkbox, 3, 2, 1, 1)
        self.shift_tue_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_tue_checkbox.setObjectName("shift_tue_checkbox")
        self.gridLayout.addWidget(self.shift_tue_checkbox, 4, 0, 1, 1)
        self.shift_sat_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_sat_checkbox.setObjectName("shift_sat_checkbox")
        self.gridLayout.addWidget(self.shift_sat_checkbox, 4, 2, 1, 1)
        self.shift_wed_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_wed_checkbox.setObjectName("shift_wed_checkbox")
        self.gridLayout.addWidget(self.shift_wed_checkbox, 5, 0, 1, 2)
        self.shift_sun_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_sun_checkbox.setObjectName("shift_sun_checkbox")
        self.gridLayout.addWidget(self.shift_sun_checkbox, 5, 2, 1, 1)
        self.shift_thu_checkbox = QtGui.QCheckBox(shift_popup)
        self.shift_thu_checkbox.setObjectName("shift_thu_checkbox")
        self.gridLayout.addWidget(self.shift_thu_checkbox, 6, 0, 1, 2)
        self.shift_intime_timeedit = QtGui.QTimeEdit(shift_popup)
        self.shift_intime_timeedit.setObjectName("shift_intime_timeedit")
        self.gridLayout.addWidget(self.shift_intime_timeedit, 1, 1, 1, 2)
        self.shift_outtime_timeedit = QtGui.QTimeEdit(shift_popup)
        self.shift_outtime_timeedit.setObjectName("shift_outtime_timeedit")
        self.gridLayout.addWidget(self.shift_outtime_timeedit, 2, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.shift_delete_button = QtGui.QPushButton(shift_popup)
        self.shift_delete_button.setObjectName("shift_delete_button")
        self.gridLayout_2.addWidget(self.shift_delete_button, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.shift_save_button = QtGui.QPushButton(shift_popup)
        self.shift_save_button.setObjectName("shift_save_button")
        self.gridLayout_2.addWidget(self.shift_save_button, 1, 2, 1, 1)

        self.retranslateUi(shift_popup)
        QtCore.QMetaObject.connectSlotsByName(shift_popup)
        shift_popup.setTabOrder(self.shift_name_linedit, self.shift_intime_timeedit)
        shift_popup.setTabOrder(self.shift_intime_timeedit, self.shift_outtime_timeedit)
        shift_popup.setTabOrder(self.shift_outtime_timeedit, self.shift_mon_checkbox)
        shift_popup.setTabOrder(self.shift_mon_checkbox, self.shift_tue_checkbox)
        shift_popup.setTabOrder(self.shift_tue_checkbox, self.shift_wed_checkbox)
        shift_popup.setTabOrder(self.shift_wed_checkbox, self.shift_thu_checkbox)
        shift_popup.setTabOrder(self.shift_thu_checkbox, self.shift_fri_checkbox)
        shift_popup.setTabOrder(self.shift_fri_checkbox, self.shift_sat_checkbox)
        shift_popup.setTabOrder(self.shift_sat_checkbox, self.shift_sun_checkbox)
        shift_popup.setTabOrder(self.shift_sun_checkbox, self.shift_save_button)
        shift_popup.setTabOrder(self.shift_save_button, self.shift_delete_button)

    def retranslateUi(self, shift_popup):
        shift_popup.setWindowTitle(QtGui.QApplication.translate("shift_popup", "Shift", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("shift_popup", "Slot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("shift_popup", "In Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("shift_popup", "Out Time", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_mon_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_fri_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_tue_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_sat_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_wed_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_sun_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_thu_checkbox.setText(QtGui.QApplication.translate("shift_popup", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_intime_timeedit.setDisplayFormat(QtGui.QApplication.translate("shift_popup", "hh:mm AP", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_outtime_timeedit.setDisplayFormat(QtGui.QApplication.translate("shift_popup", "hh:mm AP", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_delete_button.setText(QtGui.QApplication.translate("shift_popup", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_save_button.setText(QtGui.QApplication.translate("shift_popup", "Save", None, QtGui.QApplication.UnicodeUTF8))

